# NumPy 

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Installation Instructions

If using Anaconda Distribution

    conda install numpy 
    
If using default python
    
    pip install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Importing NumPy

In [3]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d.

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,21,3)

array([ 0,  3,  6,  9, 12, 15, 18])

### zeros and ones

Generate arrays of zeros or ones

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [26]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [27]:
np.ones(3)

array([ 1.,  1.,  1.])

In [28]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [11]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [12]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

In [16]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [20]:
np.random.rand(5)

array([ 0.35145812,  0.33888622,  0.23734774,  0.81641304,  0.6548817 ])

In [8]:
np.random.rand(5,5)

array([[ 0.33945124,  0.88824991,  0.24806973,  0.58408881,  0.56581065],
       [ 0.13701233,  0.7999996 ,  0.03604745,  0.36137008,  0.53121371],
       [ 0.7302075 ,  0.30177925,  0.48615437,  0.75940482,  0.25654517],
       [ 0.05742748,  0.17354481,  0.8234161 ,  0.87076978,  0.54588875],
       [ 0.29550638,  0.84501404,  0.62824673,  0.73926444,  0.90725122]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [9]:
np.random.randn(2)

array([-2.40654487,  1.65544121])

In [21]:
np.random.randn(5,5)

array([[-0.09538524, -0.10147398, -0.65826211,  0.08327002, -0.00849849],
       [ 0.14887261,  1.79583666,  0.47739698, -0.13420822, -1.21879867],
       [-0.1709158 ,  0.7118268 , -1.50779898,  0.22141161, -1.86179918],
       [-0.71566991, -0.33723139, -1.23371845, -0.51083787,  2.01208812],
       [ 0.58009567, -0.07946711, -3.1065335 , -0.33314279,  0.32049911]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [23]:
np.random.randint(1,100)

30

In [12]:
np.random.randint(1,100,10)

array([30, 86, 16, 45, 73, 63, 90,  3, 74, 64])

## Array Attributes and Methods

In [34]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
ranarr

array([10, 42, 37, 43, 17, 39,  2, 35, 32,  7])

## Reshape
Returns an array containing the same data with a new shape.

In [27]:
ranarr.reshape(2,5)

array([[37, 34, 18, 20, 46],
       [42, 44,  1, 26, 14]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [17]:
ranarr

array([10, 42, 37, 43, 17, 39,  2, 35, 32,  7])

In [18]:
ranarr.max()

43

In [19]:
ranarr.argmax()

3

In [20]:
ranarr.min()

2

In [21]:
ranarr.argmin()

6

## Shape

Shape is an attribute that arrays have (not a method):

In [36]:
# Vector
arr.shape

(25,)

In [37]:
# Notice the two sets of brackets
arr.reshape(1,25)
arr.shape

(25,)

In [39]:
arr.reshape(1,25).shape

(1, 25)

In [25]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [40]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [41]:
arr.dtype

dtype('int64')